### ISSUE TITLE
add Ende data

### ISSUE THREAD

**Issue by Bibiko** [intercontinental-dictionary-series/ids#4] opened 2019-10-03 09:08 UTC

**Comment by LinguList** [comment] 2019-10-03 09:09
What is Ende data?

**Comment by Bibiko** [comment] 2019-10-03 09:12
https://katelynnlindsey.weebly.com/ende-language.html

**Comment by Bibiko** [comment] 2019-10-03 09:15
it belongs to the Agob language http://glottolog.org/resource/languoid/id/agob1244

**Comment by LinguList** [comment] 2019-10-03 09:16
Shouldn't this rather be moved to lexibank proper? I mean, making a lexibank dataset for this purpose, rather than adding this to a resource like IDS whihc is no longer actively maintained?

**Comment by Bibiko** [comment] 2019-10-03 09:22
it is an IDS addition and as far as I know a few more languages will come soon

**Comment by Bibiko** [comment] 2019-10-03 09:25
we can move them to lexibank as long as they appear in IDS, since they are made for it

**Comment by xrotwang** [comment] 2019-10-03 09:26
Considering that these are the first additions to IDS in a long time, it
could make sense to turn these into a separate dataset. Cohesion with IDS
would still be there, because they share the concept list. But a separate
dataset would allow for better quality control, e.g. stuff like orthography
profiles right from the start.

Hans-Jörg Bibiko <notifications@github.com> schrieb am Do., 3. Okt. 2019,
11:22:

**Comment by Bibiko** [comment] 2019-10-03 09:29
I agree, but these new ones wouldn't be reachable from ids.clld.org - correct?

**Comment by xrotwang** [comment] 2019-10-03 09:30
Why not create a dataset lexibank/idsplus  or similar? Whether the web app
at ids.clld.org serves these sets as well is a separate issue, I guess.

Robert Forkel <xrotwang@googlemail.com> schrieb am Do., 3. Okt. 2019, 11:26:

**Comment by xrotwang** [comment] 2019-10-03 09:33
The db import in `clld/ids` would need to be adapted anyway, and probably work from the CLDF data in `lexibank/ids`. If this is done, adapting it to import `lexibank/idsplus` as well would be trivial.

**Comment by Bibiko** [comment] 2019-10-03 09:37
👍

**Comment by xrotwang** [comment] 2019-10-03 09:39
An orthography profile can presumably be created following the chapter on orthography here: https://www.scribd.com/document/336567519/first-pages-of-ende-dictionary

**Comment by LinguList** [comment] 2019-10-03 09:41
I prefer splitting data, specifically for this orthography profile reason. Right now, IDS is very diverse, with respect to data sources, so splitting these data and presenting them in a merged form online, as we do in clics etc., is the best way to go.

**Comment by xrotwang** [comment] 2019-10-03 09:44
We may even turn this one language into a single (somewhat tiny) dataset. This would make the orthography profile issue more transparent and possibly also serve as example for others who may want to contribute languages to IDS. So I'm for `lexibank/ids-ende1235` or similar.

**Comment by LinguList** [comment] 2019-10-03 09:47
I did the same with two recent dataset that was prepared to supplement sagartst: see lexibank/ivanisuansu and lexibank/bodtnepal .

The great advantage is that I can handle all orthography issues already from there, but have minimal work to actually get the data in form. 

To update the sagartst, I could just use a python script now that pulls in the now three datasets and merges them.

**Comment by xrotwang** [comment] 2019-10-03 09:49
Yes, CLDF was designed with mergeability in mind after all :)
Also, people like Kate-Lynn Lindsey would get a DOI for their own contribution right after release to Zenodo, and may even be willing to help with curation.

@Bibiko what does the submitted data look like? An excel sheet, I'd guess?

**Comment by Bibiko** [comment] 2019-10-03 09:59
yes - a very clean Excel sheet with standard orthography and IPA - very straight forward to handle

**Comment by Bibiko** [comment] 2019-10-03 10:01
and it should be better `lexibank/ids-agob1244-ende`

**Comment by Bibiko** [comment] 2019-10-03 10:03
and it should be `lexibank/ids-ende1235` -  https://glottolog.org/resource/languoid/id/ende1235

**Comment by LinguList** [comment] 2019-10-03 10:04
I'd recommend to go for lindseyende, as this is following our current convention. Any update of IDS would have to store those datasets to be merged later anyway, so no need to specify it explicitly as IDS, given that it's not even clear when or if it will be updated...

**Comment by xrotwang** [comment] 2019-10-03 10:10
Yes, lindseyende seems best. If IPA is already provided, an orthography
profile could be used to cross-check - and for segmentation, still.

Johann-Mattis List <notifications@github.com> schrieb am Do., 3. Okt. 2019,
12:04:

**Comment by xrotwang** [comment] 2019-10-04 05:53
So here we go:
https://github.com/lexibank/lindseyende

@Bibiko please add the raw data here.

**Closed as completed** 2019-10-04 08:03 UTC
